/** Settlement labels grouped by main district (source: Cyprus region catalog). */
export const SETTLEMENTS_BY_MAIN: Record<
  string,
  readonly string[]
> = {
  lefkosa: [
    'Akıncılar - Lurucina',
    'Alayköy - Yerolakko',
    'Balıkesir - Balikitre',
    'Beyköy - Beyköy',
    'Cihangir - Abohor',
    'Çukurova - Kuru Manastır',
    'Değirmenlik - Kitrea',
    'Demirhan - Tirfon',
    'Dilekkaya - Aya',
    'Düzova - Eksomedoş',
    'Erdemli - Tremeşe',
    'Gayretköy - Avlona',
    'Gaziler - Piroyi',
    'Gaziköy - Afanya',
    'Gökhan - Voni',
    'Gönyeli - Gönyeli',
    'Gürpınar - Aymarina',
    'Hamitköy - Mandırez',
    'Haspolat - Mia Milia',
    'İkidere - Dyo Potami',
    'Kalavaç - Kalavaç',
    'Kanlıköy - Kanlıköy',
    'Kargı - Margo',
    'Kırıkkale - Meluşa',
    'Kırklar - Kırklar',
    'Lefkoşa - Lefkoşa',
    'Meriç - Mora',
    'Metehan - Kermiya',
    'Minareliköy - Neohorio',
    'Türkeli - Ayvasıl',
    'Yeniceköy - Yeniceköy',
    'Yenikent - Yenikent',
    'Yılmazköy - Şillura',
    'Yiğitler - Arçoz',
  ],
  gazimagusa: [
    'Akdoğan - Lisi',
    'Akova - Yipsos',
    'Alaniçi - Piperisterona',
    'Arıdamı - Artemi',
    'Aslanköy - Angastina',
    'Atlılar - Aloda',
    'Beyarmudu - Pergama',
    'Baykal',
    'Çamlıca - Küfez',
    'Çanakkale',
    'Çayönü - Kalopsida',
    'Çınarlı - Bladan',
    'Dörtyol - Prastyo',
    'Düzce - Ahna',
    'Ergenekon - Ayharida',
    'Gazimağusa',
    'Geçitkale - Lefkonuk',
    'Gönendere - Gonedra',
    'Görneç - Görneç',
    'Güvercinlik - Aheridu',
    'İncirli - Makrasiga',
    'İnönü - Sinde',
    'Korkuteli - Gaydura',
    'Köprülü - Kukla',
    'Kurudere - Musulida',
    'Mallıdağ - Melunda',
    'Mormenekşe - Limya',
    'Muratağa - Marata',
    'Mutluyaka - Stilos',
    'Nergisli - Yenağra',
    'Paşaköy - Aşa',
    'Pınarlı - Vitsada',
    'Pile - Pile',
    'Pirhan - Pirga',
    'Sandallar - Sandallar',
    'Serdarlı - Çatoz',
    'Sütlüce - İpsillat',
    'Tatlısu - Akatu',
    'Tirmen - Tirmen',
    'Turunçlu - Stroncilo',
    'Tuzla - Enkomi',
    'Türkmenköy - Gondea',
    'Ulukışla - Marotovuno',
    'Vadili - Vatili',
    'Yamaçköy - Aynikola',
    'Yeniboğaziçi - Aysergi',
    'Yıldırım - Milya',
  ],
  girne: [
    'Ağırdağ - Ağırdağ',
    'Akçiçek - Sisglibo',
    'Akdeniz - Ay. İrini',
    'Alemdağ - Agridaci',
    'Alsancak - Karava',
    'Arapköy - Arapkoy',
    'Aşağı Dikmen - Digomo',
    'Aşağı Taşkent- Sihari',
    'Bahçeli - Kalturga',
    'Beşparmak - Trabeza',
    'Beylerbeyi - Balabayıs',
    'Boğazköy - Boğaz',
    'Çamlıbel - Mirtu',
    'Çatalköy - Çatalköy',
    'Dağyolu - Fota',
    'Doğanköy - Thermia',
    'Edremit - Trimit',
    'Esentepe - Ay Guruş',
    'Geçitköy - Panagra',
    'Girne',
    'Göçeri - Bilelle',
    'Güngör - Kutsovendi',
    'Hisarköy - Gambilli',
    'Ilgaz - Fderiha',
    'İncesu - Modiyes',
    'Karaağaç - Harca',
    'Karaman - Karmi',
    'Karaoğlanoğlu - Ayorgi',
    'Karpaşa - Karpasa',
    'Karşıyaka - Vasilya',
    'Kayalar - Orga',
    'Kılıçaslan - Kördümen',
    'Koruçam - Kormacit',
    'Kozan - Larnaka tis Lapitos',
    'Kömürcü - Kömürcü',
    'Lapta - Lapithos',
    'Malatya - Balyosofo',
    'Ozanköy - Gazafana',
    'Özhan - Asomato',
    'Pınarbaşı - Gırnı',
    'Sadrazamköy - Liveraos',
    'Şirinevler - Ayermola',
    'Tepebaşı - Yorgoz',
    'Yeşiltepe - Elya',
    'Yukarı Dikmen - Digomo',
    'Yukarı Taşkent - Vuni',
    'Zeytinlik - Templos, Temroz',
  ],
  guzelyurt: [
    'Akçay - Argaca',
    'Aşağı Bostancı - Aşağı Zodya',
    'Aydınköy - Prastyo',
    'Gayretköy - Avlona',
    'Güneşköy - Nikita',
    'Güzelyurt - Omorfo',
    'Kalkanlı - Gabudi',
    'Mevlevi - Cira',
    'Serhatköy - Filya',
    'Şahinler - Masari',
    'Yayla - Siryanohori',
    'Yukarı Bostancı - Yukarı Zodya',
    'Yuvacık - Hrisilyu',
    'Zümrütköy - Gadagopya',
  ],
  iskele: [
    'Adaçay - Melanağra',
    'Ağıllar - Mandres',
    'Altınova - Aynakofo',
    'Ardahan - Ardana',
    'Avtepe - Ay Simon',
    'Aygün - Ayorgi',
    'Bafra - Vogolida',
    'Balalan - Planadinissa',
    'Boltaşlı - Litrangomi',
    'Boğaz - Boğaz',
    'Boğaziçi - Lapatos',
    'Boğaztepe - Monarga',
    'Büyükkonuk - Komikebir',
    'Çayırova - Aytotoro',
    'Derince - Vatilakka',
    'Dipkarpaz - Rizokarpaso',
    'Ergazi - Ovgoroz',
    'Esenköy - Cilanemo',
    'Gelincik - Litrangomi',
    'İskele - Trikomo',
    'İskele Bahçeler (Cevizli) - Pervolia',
    'Kaleburnu - Galinoborni',
    'Kalecik - Gastria',
    'Kantara - Kantara',
    'Kaplıca - Davlos',
    'Kilitkaya - Kiridya',
    'Kumyalı - Kumyalik',
    'Kurtuluş - Avgalida',
    'Kuruova - Korovya',
    'Kuzucuk - Arnayi',
    'Mehmetçik - Galatya',
    'Mersinlik - Flamudi',
    'Ötüken - Spatarigo',
    'Pamuklu - Tavro',
    'Sazlıköy - Livadya',
    'Sınırüstü - Singrasi',
    'Sipahi - Aytrias',
    'Taşlıca - Neta',
    'Topçuköy - Topçuköy',
    'Turnalar - Gerani',
    'Tuzluca - Batrıç',
    'Yarköy - Ayilya',
    'Yedikonuk - Eftagomi',
    'Yeni Erenköy - Yalusa',
    'Yeşilköy - Ay Andronigo',
    'Zeybekköy - Ayestat',
    'Ziyamet - Ziyamet',
  ],
  lefke: [
    'Aplıç - Apliki',
    'Bademliköy - Lutro',
    'Bağlıköy - Ambeligu',
    'Cengizköy - Peristeronari',
    'Çamlıköy - Kalo Horyo',
    'Denizli - İksero',
    'Doğancı - Elye',
    'Erenköy - Koççina',
    'Gaziveren - Gaziveran',
    'Gemikonağı - İksero',
    'Günebakan - Amadyes',
    'Kurutepe - Kserovuno',
    'Lefke - Lefka',
    'Madenliköy - Ay Yorgi',
    'Ömerli - Galini',
    'Şirinköy - Varisa',
    'Taşköy - Petre',
    'Taşpınar - Angolem',
    'Yedidalga - Potamos du Gambo',
    'Yeşilırmak - Limnidi',
    'Yeşilyurt - Pendaya',
  ],
};
